Repository jdf2e/nutui, pull requests merged in 2023-12, with the labels that each got.

#2720 refactor(picker, taro): modify to gen better dts
  src/packages/__VUE/picker/common.ts
  src/packages/__VUE/picker/index.taro.vue
Labels: size/L

#2721 refactor(checkbox): modify to gen better dts
  src/packages/__VUE/checkbox/__tests__/checkbox.spec.ts
  src/packages/__VUE/checkbox/common.ts
  src/packages/__VUE/checkbox/index.taro.vue
  src/packages/__VUE/checkbox/index.vue
Labels: size/XL

#2723 chore(collapse): upd type of props.modelValue
  src/packages/__VUE/collapse/index.taro.vue
  src/packages/__VUE/collapse/index.vue
Labels: size/XS

#2719 chore(deps): update
  package.json
  packages/nutui-auto-import-resolver/package.json
  packages/nutui-eslint-config/package.json
  packages/nutui-playground/package.json
  packages/nutui-prettier-plugin/package.json
  packages/nutui-taro-demo/package.json
  packages/nutui-vite-plugins/package.json
  packages/nutui-vscode-extension/package.json
  pnpm-lock.yaml
  src/packages/__VUE/popover/index.vue
  src/packages/__VUE/swiper/__tests__/index.spec.tsx
  src/packages/__VUE/tour/__tests__/tour.spec.ts
  src/packages/utils/create/component.ts
Labels: size/XXL

#2724 fix(ci): prevent actions from running on forks
  .github/workflows/github-repo-stats.yml
  .github/workflows/publish-beta.yml
  .github/workflows/sync-gitee.yml
  .github/workflows/sync-h5.yml
  .github/workflows/sync-taro.yml
Labels: size/XS

#2725 chore(uploader): upd type of props.fileList
  src/packages/__VUE/uploader/index.taro.vue
  src/packages/__VUE/uploader/index.vue
Labels: size/XS

#2727 fix(tabs): 修复 vertical 方式下标题样式错误
  src/packages/__VUE/tabs/index.scss
Labels: size/XS

#2728 fix(tabs): 修复嵌套使用时的样式错乱问题
  src/packages/__VUE/tabs/index.scss
  src/packages/__VUE/tabs/index.taro.vue
  src/packages/__VUE/tabs/index.vue
Labels: size/L

#2701 feat: radio 组件设置 button 形状时支持改变大小
  src/packages/__VUE/radio/demo.vue
  src/packages/__VUE/radio/doc.en-US.md
  src/packages/__VUE/radio/doc.md
  src/packages/__VUE/radio/doc.taro.md
  src/packages/__VUE/radio/index.scss
  src/packages/__VUE/radio/index.taro.vue
  src/packages/__VUE/radio/index.vue
  src/packages/__VUE/radio/types.ts
Labels: size/M

#2730 chore(divider): split taro demo
  packages/nutui-taro-demo/src/layout/pages/divider/basic.vue
  packages/nutui-taro-demo/src/layout/pages/divider/custom.vue
  packages/nutui-taro-demo/src/layout/pages/divider/dashed.vue
  packages/nutui-taro-demo/src/layout/pages/divider/index.vue
  packages/nutui-taro-demo/src/layout/pages/divider/position.vue
  packages/nutui-taro-demo/src/layout/pages/divider/text.vue
  packages/nutui-taro-demo/src/layout/pages/divider/vertical.vue
  src/packages/__VUE/divider/demo/index.vue
  src/packages/__VUE/divider/doc.taro.md
Labels: size/L

#2733 chore(sticky): split demo
  packages/nutui-taro-demo/src/layout/pages/sticky/basic.vue
  packages/nutui-taro-demo/src/layout/pages/sticky/index.vue
  packages/nutui-taro-demo/src/layout/pages/sticky/top.vue
  src/packages/__VUE/sticky/demo.vue
  src/packages/__VUE/sticky/demo/basic.vue
  src/packages/__VUE/sticky/demo/bottom.vue
  src/packages/__VUE/sticky/demo/container.vue
  src/packages/__VUE/sticky/demo/index.vue
  src/packages/__VUE/sticky/demo/top.vue
  src/packages/__VUE/sticky/doc.en-US.md
  src/packages/__VUE/sticky/doc.md
  src/packages/__VUE/sticky/doc.taro.md
Labels: size/L

#2737 fix(sku): 修复小程序下选项内容的滚动问题
  src/packages/__VUE/sku/index.taro.vue
Labels: size/XS

#2739 fix(navbar): 修复标题居中等样式问题
  src/packages/__VUE/navbar/index.scss
Labels: size/S

#2740 chore(button & grid): update taro demo
  packages/nutui-taro-demo/src/basic/pages/button/icon.vue
  packages/nutui-taro-demo/src/layout/pages/grid/basic.vue
  packages/nutui-taro-demo/src/layout/pages/grid/column.vue
  packages/nutui-taro-demo/src/layout/pages/grid/gutter.vue
  packages/nutui-taro-demo/src/layout/pages/grid/horizontal.vue
  packages/nutui-taro-demo/src/layout/pages/grid/reverse.vue
  packages/nutui-taro-demo/src/layout/pages/grid/square.vue
Labels: size/S

#2704 解决nut-input-number组件在ios中点击小数点后会清空输入框的问题
  src/packages/__VUE/inputnumber/index.taro.vue
  src/packages/__VUE/inputnumber/index.vue
Labels: size/XS

#2743 chore(radio): improve type def
  src/packages/__VUE/radio/demo.vue
  src/packages/__VUE/radio/index.scss
  src/packages/__VUE/radio/index.taro.vue
  src/packages/__VUE/radio/index.vue
  src/packages/__VUE/radio/types.ts
  src/packages/__VUE/radiogroup/index.scss
  src/packages/__VUE/radiogroup/index.taro.vue
  src/packages/__VUE/radiogroup/index.vue
Labels: size/M

#2748 chore(searchbar): improve type def
  src/packages/__VUE/searchbar/index.taro.vue
  src/packages/__VUE/searchbar/index.vue
  src/packages/__VUE/searchbar/type.ts
  src/packages/__VUE/searchbar/types.ts
Labels: size/S

#2752 chore(drag): split demo
  packages/nutui-taro-demo/src/feedback/pages/drag/basic.vue
  packages/nutui-taro-demo/src/feedback/pages/drag/direction.vue
  packages/nutui-taro-demo/src/feedback/pages/drag/index.vue
  src/packages/__VUE/drag/demo.vue
  src/packages/__VUE/drag/demo/attract.vue
  src/packages/__VUE/drag/demo/basic.vue
  src/packages/__VUE/drag/demo/boundary.vue
  src/packages/__VUE/drag/demo/direction.vue
  src/packages/__VUE/drag/demo/index.vue
  src/packages/__VUE/drag/doc.en-US.md
  src/packages/__VUE/drag/doc.md
  src/packages/__VUE/drag/doc.taro.md
Labels: size/L

#2753 chore(drag): improve type def
  src/packages/__VUE/drag/index.taro.vue
  src/packages/__VUE/drag/index.vue
  src/packages/__VUE/drag/types.ts
Labels: size/S

#2764 chore(steps): improve type def
  src/packages/__VUE/steps/index.taro.vue
  src/packages/__VUE/steps/index.vue
  src/packages/__VUE/steps/types.ts
Labels: size/S

#2766 chore(pagination): improve type def
  src/packages/__VUE/pagination/index.taro.vue
  src/packages/__VUE/pagination/index.vue
  src/packages/__VUE/pagination/types.ts
Labels: size/S

#2746 feat(watermark): 水印支持多行文字
  packages/nutui-taro-demo/src/exhibition/pages/watermark/index.vue
  src/packages/__VUE/watermark/demo.vue
  src/packages/__VUE/watermark/doc.en-US.md
  src/packages/__VUE/watermark/doc.md
  src/packages/__VUE/watermark/doc.taro.md
  src/packages/__VUE/watermark/index.taro.vue
  src/packages/__VUE/watermark/index.vue
Labels: size/L

#2774 fix(tabs): 修复 iOS 下 smile 类型激活条展示问题
  src/packages/__VUE/tabs/index.scss
Labels: size/XS

#2768 fix(textarea): 修复h5下双向绑定失效的问题 (#2767)
  src/packages/__VUE/textarea/index.taro.vue
Labels: size/XS

#2775 fix(tabbar): 修复 useTaroRect 报错问题
  src/packages/__VUE/tabbar/index.taro.vue
Labels: size/S

#2783 fix(input-number): 修复 disabled 下未禁用点击问题
  src/packages/__VUE/inputnumber/index.taro.vue
  src/packages/__VUE/inputnumber/index.vue
Labels: size/XS

#2749 fix(tabs): horizontal方向占位元素宽度错误
  src/packages/__VUE/tabs/index.scss
  src/packages/__VUE/tabs/index.taro.vue
Labels: size/S

#2788 chore(tabs): improve type def
  src/packages/__VUE/tabs/index.taro.vue
  src/packages/__VUE/tabs/index.vue
  src/packages/__VUE/tabs/types.ts
Labels: size/M

#2789 feat(tabs, taro): 开启 title-scroll 时不再需要设置 name
  src/packages/__VUE/tabs/doc.md
  src/packages/__VUE/tabs/doc.taro.md
  src/packages/__VUE/tabs/index.taro.vue
Labels: size/M

#2791 fix(ellipsis): 修复taro端文本省略失效
  src/packages/__VUE/ellipsis/index.taro.vue
Labels: size/S

#2792 fix: remove font-family style
  packages/nutui-taro-demo/src/exhibition/pages/skeleton/sub.vue
  src/packages/__VUE/category/index.scss
  src/packages/__VUE/categorypane/index.scss
  src/packages/__VUE/countup/index.scss
  src/packages/__VUE/ecard/index.scss
  src/packages/__VUE/popover/index.scss
  src/packages/__VUE/skeleton/demo/sub.vue
  src/packages/__VUE/textarea/index.scss
  src/packages/__VUE/video/demo.vue
Labels: size/S

#2794 chore(collapse): remove unused prop
  src/packages/__VUE/collapseitem/index.taro.vue
  src/packages/__VUE/collapseitem/index.vue
Labels: size/XS

#2801 fix(tabs, taro): 修复 placeholder 展示错误
  src/packages/__VUE/tabs/index.taro.vue
Labels: size/XS

#2802 fix(cascader): 修复内部 tabs 标题样式
  src/packages/__VUE/cascader/index.scss
Labels: size/XS

#2806 chore(deps): update taro to v3.6.21
  package.json
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
Labels: size/XL

#2808 chore(audio): improve type def
  src/packages/__VUE/audio/index.vue
  src/packages/__VUE/audio/types.ts
  src/packages/__VUE/audiooperate/index.vue
  src/packages/__VUE/audiooperate/types.ts
Labels: size/S

#2811 chore(deps): update version
  package.json
  packages/nutui-auto-import-resolver/package.json
  packages/nutui-eslint-config/package.json
  packages/nutui-playground/package.json
  packages/nutui-playground/src/download/template/package.json
  packages/nutui-prettier-plugin/package.json
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
  src/sites/doc/components/demo-block/package.json
Labels: size/XXL

#2812 chore(deps): bump to vue 3.4 🏀
  package.json
  packages/nutui-playground/package.json
  packages/nutui-playground/src/download/template/package.json
  packages/nutui-taro-demo/package.json
  packages/nutui-taro-demo/tsconfig.json
  pnpm-lock.yaml
  src/sites/doc/components/demo-block/package.json
  tsconfig.json
Labels: size/L
