Repository jdf2e/nutui, pull requests merged in 2024-05, with the labels that each got.

#3001 refactor(input): move to script setup
  src/config.json
  src/packages/__VUE/input/doc.en-US.md
  src/packages/__VUE/input/doc.md
  src/packages/__VUE/input/doc.taro.md
  src/packages/__VUE/input/index.taro.ts
  src/packages/__VUE/input/index.taro.vue
  src/packages/__VUE/input/index.ts
  src/packages/__VUE/input/index.vue
  src/packages/__VUE/input/input.taro.vue
  src/packages/__VUE/input/input.vue
  src/packages/__VUE/input/types.ts
  src/packages/__VUE/input/util.ts
  src/packages/__VUE/invoice/invoice.taro.vue
  src/packages/__VUE/invoice/invoice.vue
Labels: size/XXL

#3058 refactor(image): move to script setup
  src/config.json
  src/packages/__VUE/image/__tests__/__snapshots__/image.spec.tsx.snap
  src/packages/__VUE/image/__tests__/image.spec.tsx
  src/packages/__VUE/image/doc.en-US.md
  src/packages/__VUE/image/doc.md
  src/packages/__VUE/image/image.taro.vue
  src/packages/__VUE/image/image.vue
  src/packages/__VUE/image/index.taro.ts
  src/packages/__VUE/image/index.taro.vue
  src/packages/__VUE/image/index.ts
  src/packages/__VUE/image/index.vue
  src/packages/__VUE/image/types.ts
Labels: size/L

#3059 feat(number-keyboard): 新增 confirm 事件
  src/packages/__VUE/numberkeyboard/doc.en-US.md
  src/packages/__VUE/numberkeyboard/doc.md
  src/packages/__VUE/numberkeyboard/doc.taro.md
  src/packages/__VUE/numberkeyboard/index.taro.vue
  src/packages/__VUE/numberkeyboard/index.vue
Labels: size/L

#3062 fix(countdown): emit paused
  src/packages/__VUE/countdown/__tests__/countdown.spec.tsx
  src/packages/__VUE/countdown/countdown.taro.vue
  src/packages/__VUE/countdown/countdown.vue
Labels: size/L

#3065 refactor(overlay): move to script setup
  src/config.json
  src/packages/__VUE/dialog/index.ts
  src/packages/__VUE/fixednav/index.taro.vue
  src/packages/__VUE/fixednav/index.vue
  src/packages/__VUE/imagepreview/index.ts
  src/packages/__VUE/overlay/doc.en-US.md
  src/packages/__VUE/overlay/doc.md
  src/packages/__VUE/overlay/doc.taro.md
  src/packages/__VUE/overlay/index.taro.ts
  src/packages/__VUE/overlay/index.taro.vue
  src/packages/__VUE/overlay/index.ts
  src/packages/__VUE/overlay/index.vue
  src/packages/__VUE/overlay/overlay.taro.vue
  src/packages/__VUE/overlay/overlay.vue
  src/packages/__VUE/popup/index.taro.vue
  src/packages/__VUE/popup/index.vue
  src/packages/utils/index.ts
Labels: size/L

#3066 refactor(watermark): move to script setup
  src/config.json
  src/packages/__VUE/watermark/__tests__/__snapshots__/watermark.spec.tsx.snap
  src/packages/__VUE/watermark/__tests__/watermark.spec.tsx
  src/packages/__VUE/watermark/doc.en-US.md
  src/packages/__VUE/watermark/doc.md
  src/packages/__VUE/watermark/doc.taro.md
  src/packages/__VUE/watermark/index.taro.ts
  src/packages/__VUE/watermark/index.taro.vue
  src/packages/__VUE/watermark/index.ts
  src/packages/__VUE/watermark/index.vue
  src/packages/__VUE/watermark/watermark.taro.vue
  src/packages/__VUE/watermark/watermark.vue
Labels: size/XL

#3070 test(searchbar): update
  src/packages/__VUE/searchbar/__tests__/__snapshots__/searchbar.spec.tsx.snap
  src/packages/__VUE/searchbar/__tests__/searchbar.spec.ts
  src/packages/__VUE/searchbar/__tests__/searchbar.spec.tsx
  src/packages/__VUE/searchbar/index.vue
Labels: size/L

#3072 fix(sticky): 修复滚动事件的监听方式
  src/packages/__VUE/sticky/index.taro.vue
Labels: size/XS

#3075 chore(deps): bump eslint to v9
  package.json
  packages/nutui-eslint-config/index.js
  packages/nutui-eslint-config/package.json
  packages/nutui-touch-emulator/src/index.js
  packages/nutui-vite-plugins/src/markdown.ts
  pnpm-lock.yaml
  src/packages/__VUE/noticebar/index.taro.vue
  src/packages/__VUE/sticky/__tests__/index.spec.ts
  src/packages/utils/touchEmulator.js
Labels: size/L

#3082 docs(dialog): 增加 lock-scroll 说明
  src/packages/__VUE/dialog/doc.taro.md
Labels: size/S

#3084 fix(textarea): 修复 slot 嵌套使用 textarea 时的输入失焦问题
  src/packages/__VUE/textarea/textarea.taro.vue
Labels: size/XS

#3085 style: hidden scrollbar by default
  src/packages/__VUE/elevator/index.scss
  src/packages/__VUE/list/index.scss
  src/packages/__VUE/menuitem/index.scss
Labels: size/S

#3091 chore(deps): bump taro to v3.6.30
  package.json
  packages/nutui-taro-demo/config/index.ts
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
Labels: size/XL

#3088 修正参数名
  src/packages/__VUE/input/doc.en-US.md
  src/packages/__VUE/input/doc.md
  src/packages/__VUE/input/doc.taro.md
Labels: size/XS
