Repository jdf2e/nutui, pull requests merged in 2024-07, with the labels that each got.

#3119 chore(deps): update
  package.json
  packages/nutui-auto-import-resolver/package.json
  packages/nutui-playground/package.json
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
  src/packages/__VUE/ecard/__tests__/__snapshots__/index.spec.ts.snap
  src/packages/__VUE/input/__tests__/__snapshots__/input.spec.ts.snap
  src/packages/__VUE/invoice/__tests__/__snapshots__/invoice.spec.tsx.snap
  src/packages/__VUE/searchbar/__tests__/__snapshots__/searchbar.spec.tsx.snap
Labels: size/XXL

#3120 chore(deps): update
  package.json
  packages/nutui-eslint-config/package.json
  packages/nutui-prettier-plugin/package.json
  packages/nutui-taro-demo/src/utils/useTranslate.ts
  pnpm-lock.yaml
  src/packages/__VUE/tabbar/__tests__/index.spec.tsx
  src/sites/assets/util/useTranslate.ts
  src/sites/utils/useTranslate.ts
Labels: size/L

#3111 fix(range): 修复使用 step 时未考虑 min 值的处理
  src/packages/__VUE/range/index.taro.vue
Labels: size/XS

#3060 feat(tabbar): add prop before-switch
  packages/nutui-eslint-config/index.js
  packages/nutui-taro-demo/src/nav/pages/tabbar/before-switch.vue
  packages/nutui-taro-demo/src/nav/pages/tabbar/index.vue
  src/packages/__VUE/tabbar/__tests__/__snapshots__/index.spec.tsx.snap
  src/packages/__VUE/tabbar/__tests__/index.spec.tsx
  src/packages/__VUE/tabbar/demo/before-switch.vue
  src/packages/__VUE/tabbar/demo/index.vue
  src/packages/__VUE/tabbar/doc.en-US.md
  src/packages/__VUE/tabbar/doc.md
  src/packages/__VUE/tabbar/doc.taro.md
  src/packages/__VUE/tabbar/tabbar.taro.vue
  src/packages/__VUE/tabbar/tabbar.vue
  src/packages/__VUE/tabbaritem/tabbar-item.taro.vue
  src/packages/__VUE/tabbaritem/tabbar-item.vue
Labels: size/L

#3122 fix(calendarcard): 修复ios端设置disableDay不生效问题
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/disable.vue
  src/packages/__VUE/calendarcard/demo/disable.vue
Labels: size/XS

#3123 fix: 修复 range-component 在百度小程序下点击获取元素位置信息报错
  src/packages/__VUE/range/index.taro.vue
Labels: size/S

#3127 feat(picker): 为当前选中的 picker-roller-item 新增类名
  src/packages/__VUE/picker/Column.vue
Labels: size/XS

#3129 perf: 优化 empty 组件判断 image 是否为一个有效的资源链接
  src/packages/__VUE/empty/empty.taro.vue
  src/packages/__VUE/empty/empty.vue
Labels: size/S
