Repository jdf2e/nutui, pull requests merged in 2024-03, with the labels that each got.

#2939 chore(deps): update to taro 3.6.24
  package.json
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
Labels: size/XL

#2947 refactor(animate): move to script setup
  src/config.json
  src/packages/__VUE/animate/__tests__/animate.spec.ts
  src/packages/__VUE/animate/animate.taro.vue
  src/packages/__VUE/animate/animate.vue
  src/packages/__VUE/animate/doc.en-US.md
  src/packages/__VUE/animate/doc.md
  src/packages/__VUE/animate/doc.taro.md
  src/packages/__VUE/animate/index.taro.ts
  src/packages/__VUE/animate/index.taro.vue
  src/packages/__VUE/animate/index.ts
  src/packages/__VUE/animate/index.vue
  src/packages/__VUE/animate/types.ts
Labels: size/L

#2951 refactor(layout): move to script setup
  src/config.json
  src/packages/__VUE/col/__tests__/index.spec.ts
  src/packages/__VUE/col/col.taro.vue
  src/packages/__VUE/col/col.vue
  src/packages/__VUE/col/index.taro.ts
  src/packages/__VUE/col/index.taro.vue
  src/packages/__VUE/col/index.ts
  src/packages/__VUE/col/index.vue
  src/packages/__VUE/layout/doc.en-US.md
  src/packages/__VUE/layout/doc.md
  src/packages/__VUE/layout/doc.taro.md
  src/packages/__VUE/layout/index.taro.ts
  src/packages/__VUE/layout/index.ts
  src/packages/__VUE/layout/layout.taro.vue
  src/packages/__VUE/layout/layout.vue
  src/packages/__VUE/row/__tests__/index.spec.ts
  src/packages/__VUE/row/index.taro.ts
  src/packages/__VUE/row/index.taro.vue
  src/packages/__VUE/row/index.ts
  src/packages/__VUE/row/index.vue
  src/packages/__VUE/row/row.taro.vue
  src/packages/__VUE/row/row.vue
Labels: size/L

#2952 refactor(price): move to script setup
  src/config.json
  src/packages/__VUE/card/index.taro.vue
  src/packages/__VUE/card/index.vue
  src/packages/__VUE/price/__tests__/price.spec.ts
  src/packages/__VUE/price/doc.en-US.md
  src/packages/__VUE/price/doc.md
  src/packages/__VUE/price/doc.taro.md
  src/packages/__VUE/price/index.taro.ts
  src/packages/__VUE/price/index.taro.vue
  src/packages/__VUE/price/index.ts
  src/packages/__VUE/price/index.vue
  src/packages/__VUE/price/price.taro.vue
  src/packages/__VUE/price/price.vue
  src/packages/__VUE/sku/components/SkuHeader.taro.vue
  src/packages/__VUE/sku/components/SkuHeader.vue
Labels: size/XL

#2958 fix(form): 修复 disabled 关联子组件收集问题
  src/packages/__VUE/form/common.ts
  src/packages/__VUE/form/form.taro.vue
  src/packages/__VUE/form/form.vue
  src/packages/__VUE/form/types.ts
  src/packages/__VUE/formitem/form-item.taro.vue
  src/packages/__VUE/formitem/form-item.vue
Labels: size/S

#2959 feat(switch): add disabled prop & mark disable deprecated
  packages/nutui-taro-demo/src/feedback/pages/switch/disabled.vue
  src/packages/__VUE/switch/__tests__/switch.spec.ts
  src/packages/__VUE/switch/demo/disabled.vue
  src/packages/__VUE/switch/doc.en-US.md
  src/packages/__VUE/switch/doc.md
  src/packages/__VUE/switch/doc.taro.md
  src/packages/__VUE/switch/index.scss
  src/packages/__VUE/switch/index.taro.vue
  src/packages/__VUE/switch/index.vue
Labels: size/M

#2936 fix(popup): 修复 update:visible 事件关闭时重复调用
  src/packages/__VUE/popup/index.taro.vue
  src/packages/__VUE/popup/index.vue
Labels: size/M

#2964 refactor(input-number): move to setup script
  src/config.json
  src/packages/__VUE/animate/doc.en-US.md
  src/packages/__VUE/animate/doc.md
  src/packages/__VUE/animate/doc.taro.md
  src/packages/__VUE/ecard/index.taro.vue
  src/packages/__VUE/ecard/index.vue
  src/packages/__VUE/form/__tests__/index.spec.tsx
  src/packages/__VUE/inputnumber/__tests__/index.spec.ts
  src/packages/__VUE/inputnumber/doc.en-US.md
  src/packages/__VUE/inputnumber/doc.md
  src/packages/__VUE/inputnumber/doc.taro.md
  src/packages/__VUE/inputnumber/index.taro.ts
  src/packages/__VUE/inputnumber/index.taro.vue
  src/packages/__VUE/inputnumber/index.ts
  src/packages/__VUE/inputnumber/index.vue
  src/packages/__VUE/inputnumber/input-number.taro.vue
  src/packages/__VUE/inputnumber/input-number.vue
  src/packages/__VUE/layout/doc.en-US.md
  src/packages/__VUE/layout/doc.md
  src/packages/__VUE/layout/doc.taro.md
  src/packages/__VUE/price/doc.en-US.md
  src/packages/__VUE/price/doc.md
  src/packages/__VUE/price/doc.taro.md
  src/packages/__VUE/sku/components/SkuStepper.taro.vue
  src/packages/__VUE/sku/components/SkuStepper.vue
Labels: size/XL

#2963 fix(calendar-card): 选择范围时支持仅选择单个日期
  src/packages/__VUE/calendarcard/__tests__/calendarcard.spec.tsx
  src/packages/__VUE/calendarcard/calendar-card.taro.vue
  src/packages/__VUE/calendarcard/calendar-card.vue
Labels: size/S

#2965 chore: clean config.json
  packages/nutui-taro-demo/src/pages/index/index.vue
  scripts/createComponentMode.js
  scripts/demo.js
  scripts/generate-nutui-taro-vue.cjs
  scripts/generate-nutui.cjs
  scripts/generate-taro-route.cjs
  scripts/generate-unplugin-deps.cjs
  src/config.json
  src/packages/__VUE/calendar/index.scss
  src/packages/__VUE/calendaritem/index.scss
  src/sites/doc/components/Nav.vue
  vite.config.build.disperse.ts
Labels: size/XL

#2966 refactor(rate): move to script setup
  src/config.json
  src/packages/__VUE/comment/components/CmtHeader.taro.vue
  src/packages/__VUE/comment/components/CmtHeader.vue
  src/packages/__VUE/form/__tests__/index.spec.tsx
  src/packages/__VUE/rate/__tests__/__snapshots__/rate.spec.tsx.snap
  src/packages/__VUE/rate/__tests__/rate.spec.tsx
  src/packages/__VUE/rate/doc.en-US.md
  src/packages/__VUE/rate/doc.md
  src/packages/__VUE/rate/doc.taro.md
  src/packages/__VUE/rate/index.taro.ts
  src/packages/__VUE/rate/index.ts
  src/packages/__VUE/rate/index.vue
  src/packages/__VUE/rate/rate.taro.vue
  src/packages/__VUE/rate/rate.vue
Labels: size/XL

#2968 refactor(progress): move to script setup
  src/config.json
  src/packages/__VUE/progress/__tests__/index.spec.ts
  src/packages/__VUE/progress/doc.en-US.md
  src/packages/__VUE/progress/doc.md
  src/packages/__VUE/progress/doc.taro.md
  src/packages/__VUE/progress/index.taro.ts
  src/packages/__VUE/progress/index.taro.vue
  src/packages/__VUE/progress/index.ts
  src/packages/__VUE/progress/index.vue
  src/packages/__VUE/progress/progress.taro.vue
  src/packages/__VUE/progress/progress.vue
  src/packages/__VUE/uploader/index.taro.vue
  src/packages/__VUE/uploader/index.vue
Labels: size/XL

#2969 refactor(circle-progress): move to script setup
  packages/nutui-taro-demo/src/exhibition/pages/circleprogress/color.vue
  src/config.json
  src/packages/__VUE/circleprogress/__tests__/index.spec.ts
  src/packages/__VUE/circleprogress/circle-progress.taro.vue
  src/packages/__VUE/circleprogress/circle-progress.vue
  src/packages/__VUE/circleprogress/demo/color.vue
  src/packages/__VUE/circleprogress/doc.en-US.md
  src/packages/__VUE/circleprogress/doc.md
  src/packages/__VUE/circleprogress/doc.taro.md
  src/packages/__VUE/circleprogress/index.taro.ts
  src/packages/__VUE/circleprogress/index.taro.vue
  src/packages/__VUE/circleprogress/index.ts
  src/packages/__VUE/circleprogress/index.vue
Labels: size/XL

#2970 refactor(backtop): migrate to script setup
  src/config.json
  src/packages/__VUE/backtop/__tests__/backtop.spec.ts
  src/packages/__VUE/backtop/backtop.taro.vue
  src/packages/__VUE/backtop/backtop.vue
  src/packages/__VUE/backtop/doc.en-US.md
  src/packages/__VUE/backtop/doc.md
  src/packages/__VUE/backtop/doc.taro.md
  src/packages/__VUE/backtop/index.taro.ts
  src/packages/__VUE/backtop/index.taro.vue
  src/packages/__VUE/backtop/index.ts
  src/packages/__VUE/backtop/index.vue
Labels: size/XL

#2975 refactor(swipe): move to script setup
  src/config.json
  src/packages/__VUE/addresslist/components/GeneralShell.taro.vue
  src/packages/__VUE/addresslist/components/GeneralShell.vue
  src/packages/__VUE/swipe/__tests__/swipe.spec.tsx
  src/packages/__VUE/swipe/doc.en-US.md
  src/packages/__VUE/swipe/doc.md
  src/packages/__VUE/swipe/doc.taro.md
  src/packages/__VUE/swipe/index.taro.ts
  src/packages/__VUE/swipe/index.taro.vue
  src/packages/__VUE/swipe/index.ts
  src/packages/__VUE/swipe/index.vue
  src/packages/__VUE/swipe/swipe.taro.vue
  src/packages/__VUE/swipe/swipe.vue
  src/packages/__VUE/swipe/types.ts
  src/packages/__VUE/swipegroup/index.taro.ts
  src/packages/__VUE/swipegroup/index.taro.vue
  src/packages/__VUE/swipegroup/index.ts
  src/packages/__VUE/swipegroup/index.vue
  src/packages/__VUE/swipegroup/swipe-group.taro.vue
  src/packages/__VUE/swipegroup/swipe-group.vue
Labels: size/XXL

#2978 refactor(tag): move to script setup
  src/config.json
  src/packages/__VUE/backtop/doc.taro.md
  src/packages/__VUE/card/index.taro.vue
  src/packages/__VUE/card/index.vue
  src/packages/__VUE/tag/doc.en-US.md
  src/packages/__VUE/tag/doc.md
  src/packages/__VUE/tag/doc.taro.md
  src/packages/__VUE/tag/index.taro.ts
  src/packages/__VUE/tag/index.taro.vue
  src/packages/__VUE/tag/index.ts
  src/packages/__VUE/tag/index.vue
  src/packages/__VUE/tag/tag.taro.vue
  src/packages/__VUE/tag/tag.vue
  src/packages/__VUE/tag/types.ts
Labels: size/L

#2979 refactor(navbar): move to script setup
  src/config.json
  src/packages/__VUE/navbar/doc.en-US.md
  src/packages/__VUE/navbar/doc.md
  src/packages/__VUE/navbar/doc.taro.md
  src/packages/__VUE/navbar/index.taro.ts
  src/packages/__VUE/navbar/index.taro.vue
  src/packages/__VUE/navbar/index.ts
  src/packages/__VUE/navbar/index.vue
  src/packages/__VUE/navbar/navbar.taro.vue
  src/packages/__VUE/navbar/navbar.vue
Labels: size/XL

#2981 refactor(invoice): move to script setup
  packages/nutui-taro-demo/src/business/pages/invoice/basic.vue
  src/config.json
  src/packages/__VUE/invoice/demo/basic.vue
  src/packages/__VUE/invoice/doc.en-US.md
  src/packages/__VUE/invoice/doc.md
  src/packages/__VUE/invoice/doc.taro.md
  src/packages/__VUE/invoice/index.taro.ts
  src/packages/__VUE/invoice/index.taro.vue
  src/packages/__VUE/invoice/index.ts
  src/packages/__VUE/invoice/index.vue
  src/packages/__VUE/invoice/invoice.taro.vue
  src/packages/__VUE/invoice/invoice.vue
  src/packages/__VUE/invoice/types.ts
Labels: size/L

#2980 test: add some unit tests
  src/packages/__VUE/calendar/__tests__/__snapshots__/calendar.spec.tsx.snap
  src/packages/__VUE/calendar/__tests__/calendar.spec.ts
  src/packages/__VUE/calendar/__tests__/calendar.spec.tsx
  src/packages/__VUE/invoice/__tests__/__snapshots__/invoice.spec.tsx.snap
  src/packages/__VUE/invoice/__tests__/invoice.spec.tsx
  src/packages/__VUE/signature/__tests__/__snapshots__/signature.spec.tsx.snap
  src/packages/__VUE/signature/__tests__/signature.spec.tsx
  src/packages/__VUE/watermark/__tests__/__snapshots__/watermark.spec.tsx.snap
  src/packages/__VUE/watermark/__tests__/watermark.spec.tsx
Labels: size/XL

#2982 chore(site): highlight.js -> shiki
  packages/nutui-vite-plugins/package.json
  packages/nutui-vite-plugins/src/markdown.ts
  pnpm-lock.yaml
  src/sites/assets/styles/highlight.scss
Labels: size/L

#2985 docs: update List use .
  src/packages/__VUE/list/doc.md
  src/packages/__VUE/list/doc.taro.md
Labels: size/XS

#2991 refactor(empty): move to script setup
  src/config.json
  src/packages/__VUE/empty/doc.en-US.md
  src/packages/__VUE/empty/doc.md
  src/packages/__VUE/empty/doc.taro.md
  src/packages/__VUE/empty/empty.taro.vue
  src/packages/__VUE/empty/empty.vue
  src/packages/__VUE/empty/index.taro.ts
  src/packages/__VUE/empty/index.taro.vue
  src/packages/__VUE/empty/index.ts
  src/packages/__VUE/empty/index.vue
Labels: size/L

#2993 refactor(trend-arrow): move to script setup
  src/config.json
  src/packages/__VUE/trendarrow/doc.en-US.md
  src/packages/__VUE/trendarrow/doc.md
  src/packages/__VUE/trendarrow/doc.taro.md
  src/packages/__VUE/trendarrow/index.taro.ts
  src/packages/__VUE/trendarrow/index.taro.vue
  src/packages/__VUE/trendarrow/index.ts
  src/packages/__VUE/trendarrow/index.vue
  src/packages/__VUE/trendarrow/trend-arrow.taro.vue
  src/packages/__VUE/trendarrow/trend-arrow.vue
Labels: size/L

#2994 chore(tabbar): add deprecated tag
  src/packages/__VUE/tabbar/doc.en-US.md
  src/packages/__VUE/tabbar/doc.md
  src/packages/__VUE/tabbaritem/tabbar-item.taro.vue
  src/packages/__VUE/tabbaritem/tabbar-item.vue
Labels: size/M

#2992 refactor(switch): move to script setup
  src/config.json
  src/packages/__VUE/switch/doc.en-US.md
  src/packages/__VUE/switch/doc.md
  src/packages/__VUE/switch/doc.taro.md
  src/packages/__VUE/switch/index.taro.ts
  src/packages/__VUE/switch/index.taro.vue
  src/packages/__VUE/switch/index.ts
  src/packages/__VUE/switch/index.vue
  src/packages/__VUE/switch/switch.taro.vue
  src/packages/__VUE/switch/switch.vue
Labels: size/L

#2996 fix(tabs): 修复 vertical 方式 tab 数量过多时滚动定位不准确的问题
  src/packages/__VUE/tabs/__tests__/index.spec.tsx
  src/packages/__VUE/tabs/index.taro.vue
  src/packages/__VUE/tabs/index.vue
Labels: size/L

#3000 refactor(indicator): move to script setup
  src/config.json
  src/packages/__VUE/indicator/doc.en-US.md
  src/packages/__VUE/indicator/doc.md
  src/packages/__VUE/indicator/doc.taro.md
  src/packages/__VUE/indicator/index.taro.ts
  src/packages/__VUE/indicator/index.taro.vue
  src/packages/__VUE/indicator/index.ts
  src/packages/__VUE/indicator/index.vue
  src/packages/__VUE/indicator/indicator.taro.vue
  src/packages/__VUE/indicator/indicator.vue
Labels: size/L

#3002 chore: add type module in taro demo
  packages/nutui-taro-demo/babel.config.cjs
  packages/nutui-taro-demo/config/dev.ts
  packages/nutui-taro-demo/config/index.ts
  packages/nutui-taro-demo/config/prod.js
  packages/nutui-taro-demo/config/prod.ts
  packages/nutui-taro-demo/package.json
  packages/nutui-taro-demo/project.config.json
  packages/nutui-taro-demo/tsconfig.json
Labels: size/M
