Repository jdf2e/nutui, pull requests merged in 2024-09, with the labels that each got.

#3188 feat(uploader): support beforeUpload in taro
  packages/nutui-prettier-plugin/index.js
  packages/nutui-taro-demo/src/dentry/pages/uploader/index.vue
  src/packages/__VUE/uploader/doc.taro.md
  src/packages/__VUE/uploader/index.taro.vue
Labels: size/M

#3194 Fix a typo in README.md
  README.md
Labels: size/XS

#3197 chore: replace local prettier plugin with npm package
  .prettierrc
  package.json
  packages/nutui-prettier-plugin/index.js
  packages/nutui-prettier-plugin/package.json
  pnpm-lock.yaml
Labels: size/L

#3206 chore(deps): update vue/core to v3.5.10
  package.json
  pnpm-lock.yaml
  publish/nutui-taro/README.md
  publish/nutui/README.md
  src/packages/__VUE/comment/components/CmtImages.taro.vue
  src/packages/__VUE/comment/components/CmtImages.vue
  src/packages/__VUE/comment/index.taro.vue
  src/packages/__VUE/comment/index.vue
  src/packages/__VUE/comment/type.ts
  src/packages/__VUE/sku/components/SkuSelect.vue
  src/packages/__VUE/sku/components/SkuStepper.vue
  src/packages/__VUE/sku/type.ts
Labels: size/L
