Repository jdf2e/nutui, pull requests merged in 2024-04, with the labels that each got.

#2997 refactor(textarea): move to script setup
  src/config.json
  src/packages/__VUE/textarea/__tests__/textarea.spec.ts
  src/packages/__VUE/textarea/doc.en-US.md
  src/packages/__VUE/textarea/doc.md
  src/packages/__VUE/textarea/doc.taro.md
  src/packages/__VUE/textarea/index.taro.ts
  src/packages/__VUE/textarea/index.taro.vue
  src/packages/__VUE/textarea/index.ts
  src/packages/__VUE/textarea/index.vue
  src/packages/__VUE/textarea/textarea.taro.vue
  src/packages/__VUE/textarea/textarea.vue
Labels: size/XL

#3007 refactor(skeleton): move to script setup
  src/config.json
  src/packages/__VUE/backtop/doc.en-US.md
  src/packages/__VUE/backtop/doc.md
  src/packages/__VUE/backtop/doc.taro.md
  src/packages/__VUE/empty/doc.en-US.md
  src/packages/__VUE/empty/doc.md
  src/packages/__VUE/empty/doc.taro.md
  src/packages/__VUE/indicator/doc.en-US.md
  src/packages/__VUE/indicator/doc.md
  src/packages/__VUE/indicator/doc.taro.md
  src/packages/__VUE/skeleton/__tests__/__snapshots__/skeleton.spec.ts.snap
  src/packages/__VUE/skeleton/__tests__/__snapshots__/skeleton.spec.tsx.snap
  src/packages/__VUE/skeleton/__tests__/skeleton.spec.ts
  src/packages/__VUE/skeleton/__tests__/skeleton.spec.tsx
  src/packages/__VUE/skeleton/doc.en-US.md
  src/packages/__VUE/skeleton/doc.md
  src/packages/__VUE/skeleton/doc.taro.md
  src/packages/__VUE/skeleton/index.taro.ts
  src/packages/__VUE/skeleton/index.taro.vue
  src/packages/__VUE/skeleton/index.ts
  src/packages/__VUE/skeleton/index.vue
  src/packages/__VUE/skeleton/skeleton.taro.vue
  src/packages/__VUE/skeleton/skeleton.vue
  src/packages/__VUE/swipe/doc.en-US.md
  src/packages/__VUE/swipe/doc.md
  src/packages/__VUE/swipe/doc.taro.md
  src/packages/__VUE/switch/doc.en-US.md
  src/packages/__VUE/switch/doc.md
  src/packages/__VUE/switch/doc.taro.md
  src/packages/__VUE/trendarrow/doc.en-US.md
  src/packages/__VUE/trendarrow/doc.md
  src/packages/__VUE/trendarrow/doc.taro.md
Labels: size/XL

#3008 feat(input-number): 支持透传属性至 input 元素
  src/packages/__VUE/inputnumber/__tests__/__snapshots__/index.spec.tsx.snap
  src/packages/__VUE/inputnumber/__tests__/index.spec.tsx
  src/packages/__VUE/inputnumber/doc.en-US.md
  src/packages/__VUE/inputnumber/doc.md
  src/packages/__VUE/inputnumber/doc.taro.md
  src/packages/__VUE/inputnumber/input-number.taro.vue
  src/packages/__VUE/inputnumber/input-number.vue
Labels: size/M

#3013 chore(deps): typescript v5.4.4
  package.json
  packages/nutui-auto-import-resolver/package.json
  packages/nutui-taro-demo/package.json
  packages/nutui-vite-plugins/package.json
  pnpm-lock.yaml
  src/sites/doc/components/demo-block/package.json
Labels: size/L

#3015 refactor(cell): move to script setup
  src/config.json
  src/packages/__VUE/cell/cell.taro.vue
  src/packages/__VUE/cell/cell.vue
  src/packages/__VUE/cell/doc.en-US.md
  src/packages/__VUE/cell/doc.md
  src/packages/__VUE/cell/doc.taro.md
  src/packages/__VUE/cell/index.taro.ts
  src/packages/__VUE/cell/index.taro.vue
  src/packages/__VUE/cell/index.ts
  src/packages/__VUE/cell/index.vue
  src/packages/__VUE/cellgroup/cell-group.taro.vue
  src/packages/__VUE/cellgroup/cell-group.vue
  src/packages/__VUE/cellgroup/index.taro.ts
  src/packages/__VUE/cellgroup/index.ts
  src/packages/__VUE/form/form.taro.vue
  src/packages/__VUE/form/form.vue
  src/packages/__VUE/formitem/form-item.taro.vue
  src/packages/__VUE/formitem/form-item.vue
Labels: size/XL

#3023 fix: typo index.taro.vue
  src/packages/__VUE/sticky/index.taro.vue
Labels: size/XS

#3021 refactor(radio): move to script setup
  src/config.json
  src/packages/__VUE/invoice/__tests__/__snapshots__/invoice.spec.tsx.snap
  src/packages/__VUE/invoice/invoice.taro.vue
  src/packages/__VUE/invoice/invoice.vue
  src/packages/__VUE/radio/doc.en-US.md
  src/packages/__VUE/radio/doc.md
  src/packages/__VUE/radio/doc.taro.md
  src/packages/__VUE/radio/index.taro.ts
  src/packages/__VUE/radio/index.taro.vue
  src/packages/__VUE/radio/index.ts
  src/packages/__VUE/radio/index.vue
  src/packages/__VUE/radio/radio.taro.vue
  src/packages/__VUE/radio/radio.vue
  src/packages/__VUE/radiogroup/index.taro.ts
  src/packages/__VUE/radiogroup/index.taro.vue
  src/packages/__VUE/radiogroup/index.ts
  src/packages/__VUE/radiogroup/index.vue
  src/packages/__VUE/radiogroup/radio-group.taro.vue
  src/packages/__VUE/radiogroup/radio-group.vue
Labels: size/XL

#3027 chore: 优化组件 provide/inject 使用
  src/packages/__VUE/audio/index.vue
  src/packages/__VUE/audio/types.ts
  src/packages/__VUE/audiooperate/index.vue
  src/packages/__VUE/audiooperate/types.ts
  src/packages/__VUE/form/common.ts
  src/packages/__VUE/form/form.taro.vue
  src/packages/__VUE/form/form.vue
  src/packages/__VUE/formitem/form-item.taro.vue
  src/packages/__VUE/formitem/form-item.vue
  src/packages/__VUE/tabpane/index.taro.vue
  src/packages/__VUE/tabpane/index.vue
  src/packages/__VUE/tabs/index.taro.vue
  src/packages/__VUE/tabs/index.vue
  src/packages/__VUE/tabs/types.ts
Labels: size/M

#3029 fix: warning `is not a valid value for v-model` in JetBrains IDE
  scripts/createAttributes.cjs
Labels: size/S

#3018 refactor(countdown): move to script setup
  src/config.json
  src/packages/__VUE/countdown/countdown.taro.vue
  src/packages/__VUE/countdown/countdown.vue
  src/packages/__VUE/countdown/doc.en-US.md
  src/packages/__VUE/countdown/doc.md
  src/packages/__VUE/countdown/doc.taro.md
  src/packages/__VUE/countdown/index.taro.ts
  src/packages/__VUE/countdown/index.taro.vue
  src/packages/__VUE/countdown/index.ts
  src/packages/__VUE/countdown/index.vue
  src/packages/__VUE/countdown/util.ts
Labels: size/XXL

#3022 refactor(steps): move to script setup
  src/config.json
  src/packages/__VUE/step/index.taro.ts
  src/packages/__VUE/step/index.taro.vue
  src/packages/__VUE/step/index.ts
  src/packages/__VUE/step/index.vue
  src/packages/__VUE/step/step.taro.vue
  src/packages/__VUE/step/step.vue
  src/packages/__VUE/steps/__tests__/index.spec.tsx
  src/packages/__VUE/steps/doc.en-US.md
  src/packages/__VUE/steps/doc.md
  src/packages/__VUE/steps/doc.taro.md
  src/packages/__VUE/steps/index.taro.ts
  src/packages/__VUE/steps/index.taro.vue
  src/packages/__VUE/steps/index.ts
  src/packages/__VUE/steps/index.vue
  src/packages/__VUE/steps/steps.taro.vue
  src/packages/__VUE/steps/steps.vue
  src/packages/utils/useRelation/useParent.ts
Labels: size/XL

#3037 refactor(grid): move to script setup
  src/config.json
  src/packages/__VUE/grid/common.ts
  src/packages/__VUE/grid/doc.en-US.md
  src/packages/__VUE/grid/doc.md
  src/packages/__VUE/grid/doc.taro.md
  src/packages/__VUE/grid/grid.taro.vue
  src/packages/__VUE/grid/grid.vue
  src/packages/__VUE/grid/index.taro.ts
  src/packages/__VUE/grid/index.taro.vue
  src/packages/__VUE/grid/index.ts
  src/packages/__VUE/grid/index.vue
  src/packages/__VUE/grid/types.ts
  src/packages/__VUE/griditem/grid-item.taro.vue
  src/packages/__VUE/griditem/grid-item.vue
  src/packages/__VUE/griditem/index.taro.ts
  src/packages/__VUE/griditem/index.taro.vue
  src/packages/__VUE/griditem/index.ts
  src/packages/__VUE/griditem/index.vue
  src/packages/utils/index.ts
Labels: size/XL

#3044 document(input):修复对齐方式演示代码引用错误问题
  src/packages/__VUE/input/doc.md
  src/packages/__VUE/input/doc.taro.md
Labels: size/XS

#3045 fix: cannot read properties of undefined (reading 'animatedTime')
  src/packages/__VUE/tabpane/index.taro.vue
  src/packages/__VUE/tabpane/index.vue
Labels: size/XS
