Repository jdf2e/nutui, pull requests merged in 2024-01, with the labels that each got.

#2803 feat: swiper支持修改未选中时的分页指示器的颜色
  packages/nutui-taro-demo/src/exhibition/pages/swiper/index.vue
  src/packages/__VUE/swiper/demo.vue
  src/packages/__VUE/swiper/doc.en-US.md
  src/packages/__VUE/swiper/doc.md
  src/packages/__VUE/swiper/doc.taro.md
  src/packages/__VUE/swiper/index.taro.vue
  src/packages/__VUE/swiper/index.vue
Labels: size/M

#2813 chore(deps): update version
  package.json
  packages/nutui-playground/package.json
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
Labels: size/XXL

#2814 chore: replace vite-plugin-inspect with vite-plugin-vue-devtools
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: size/L

#2809 feat: tabs使用横纵方向，标题支持左对齐
  packages/nutui-taro-demo/src/nav/pages/tabs/index.vue
  packages/nutui-taro-demo/src/nav/pages/tabs/left-align.vue
  src/packages/__VUE/tabs/demo/index.vue
  src/packages/__VUE/tabs/demo/left-align.vue
  src/packages/__VUE/tabs/doc.en-US.md
  src/packages/__VUE/tabs/doc.md
  src/packages/__VUE/tabs/doc.taro.md
  src/packages/__VUE/tabs/index.scss
  src/packages/__VUE/tabs/index.taro.vue
  src/packages/__VUE/tabs/index.vue
  src/packages/__VUE/tabs/types.ts
Labels: size/M

#2815 chore(audio): split demo
  src/packages/__VUE/audio/demo.vue
  src/packages/__VUE/audio/demo/basic.vue
  src/packages/__VUE/audio/demo/control.vue
  src/packages/__VUE/audio/demo/index.vue
  src/packages/__VUE/audio/demo/play.vue
  src/packages/__VUE/audio/demo/progress.vue
  src/packages/__VUE/audio/doc.en-US.md
  src/packages/__VUE/audio/doc.md
Labels: size/XL

#2816 perf(deps): replace lint-staged with nano-staged
  .husky/pre-commit
  commitlint.config.cjs
  package.json
  pnpm-lock.yaml
Labels: size/L

#2819 chore(image): split demo
  src/packages/__VUE/image/demo.vue
  src/packages/__VUE/image/demo/basic.vue
  src/packages/__VUE/image/demo/error.vue
  src/packages/__VUE/image/demo/fit.vue
  src/packages/__VUE/image/demo/index.vue
  src/packages/__VUE/image/demo/lazy.vue
  src/packages/__VUE/image/demo/loading.vue
  src/packages/__VUE/image/demo/position.vue
  src/packages/__VUE/image/demo/round.vue
  src/packages/__VUE/image/doc.en-US.md
  src/packages/__VUE/image/doc.md
  tsconfig.json
Labels: size/XL

#2820 docs: avatarcropper 文档修正
  src/packages/__VUE/avatarcropper/doc.en-US.md
  src/packages/__VUE/avatarcropper/doc.md
  src/packages/__VUE/avatarcropper/doc.taro.md
Labels: size/S

#2821 fix(picker): 修复 Safari 下遮罩层级样式问题
  src/packages/__VUE/picker/index.scss
Labels: size/XS

#2784 fix(datepicker): "hour-minute"类型下，修改小时不刷新分钟列的选择范围
  src/packages/__VUE/datepicker/index.taro.vue
  src/packages/__VUE/datepicker/index.vue
Labels: size/S

#2823 fix(dialog): 修复 cancel 按钮的样式问题
  src/packages/__VUE/dialog/index.scss
Labels: size/XS

#2826 fix(picker): 优化 select、cursor 样式
  src/packages/__VUE/picker/index.scss
Labels: size/XS

#2829 fix(calendar): 修复初次打开默认值定位问题
  src/packages/__VUE/calendar/index.taro.vue
  src/packages/__VUE/calendar/index.vue
  src/packages/__VUE/calendaritem/index.vue
Labels: size/M

#2824 fix(date-picker): 修复数据联动更新问题
  src/packages/__VUE/datepicker/index.taro.vue
  src/packages/__VUE/datepicker/index.vue
Labels: size/L

#2831 chore(deps): update version
  package.json
  packages/nutui-auto-import-resolver/package.json
  packages/nutui-eslint-config/package.json
  packages/nutui-playground/package.json
  packages/nutui-taro-demo/package.json
  pnpm-lock.yaml
  src/packages/__VUE/cascader/__tests__/__snapshots__/cascader.spec.ts.snap
  src/packages/__VUE/inputnumber/__tests__/index.spec.ts
Labels: size/XXL

#2818 feat: 头像裁剪 AvatarCropper 支持裁剪圆形
  src/packages/__VUE/avatar/index.scss
  src/packages/__VUE/avatarcropper/demo.vue
  src/packages/__VUE/avatarcropper/doc.en-US.md
  src/packages/__VUE/avatarcropper/doc.md
  src/packages/__VUE/avatarcropper/index.scss
  src/packages/__VUE/avatarcropper/index.vue
  src/packages/__VUE/avatarcropper/types.ts
Labels: size/M

#2834 feat(avatar-cropper, taro): 新增 shape 属性
  packages/nutui-taro-demo/src/business/pages/avatarcropper/index.vue
  src/packages/__VUE/avatarcropper/doc.en-US.md
  src/packages/__VUE/avatarcropper/doc.md
  src/packages/__VUE/avatarcropper/doc.taro.md
  src/packages/__VUE/avatarcropper/index.taro.vue
Labels: size/M

#2838 perf(calendar): demo add custom-wrapper
  packages/nutui-taro-demo/src/dentry/pages/calendar/index.vue
Labels: size/M

#2839 chore: update tsconfig.json
  tsconfig.declaration.json
  tsconfig.declaration.taro.json
Labels: size/S

#2713 refactor(button): script setup
  scripts/generate-nutui-taro-vue.cjs
  scripts/generate-nutui.cjs
  scripts/generate-types-taro.cjs
  scripts/generate-types.cjs
  src/config.json
  src/packages/__VUE/addresslist/components/GeneralShell.taro.vue
  src/packages/__VUE/addresslist/components/GeneralShell.vue
  src/packages/__VUE/addresslist/index.taro.vue
  src/packages/__VUE/addresslist/index.vue
  src/packages/__VUE/audiooperate/index.vue
  src/packages/__VUE/avatarcropper/index.taro.vue
  src/packages/__VUE/avatarcropper/index.vue
  src/packages/__VUE/button/__tests__/button.spec.ts
  src/packages/__VUE/button/button.taro.vue
  src/packages/__VUE/button/button.vue
  src/packages/__VUE/button/doc.en-US.md
  src/packages/__VUE/button/doc.md
  src/packages/__VUE/button/doc.taro.md
  src/packages/__VUE/button/index.taro.ts
  src/packages/__VUE/button/index.taro.vue
  src/packages/__VUE/button/index.ts
  src/packages/__VUE/button/index.vue
  src/packages/__VUE/button/types.ts
  src/packages/__VUE/countdown/__tests__/countdown.spec.ts
  src/packages/__VUE/dialog/index.taro.vue
  src/packages/__VUE/dialog/index.ts
  src/packages/__VUE/dialog/index.vue
  src/packages/__VUE/form/__tests__/index.spec.ts
  src/packages/__VUE/invoice/index.taro.vue
  src/packages/__VUE/invoice/index.vue
  src/packages/__VUE/signature/index.taro.vue
  src/packages/__VUE/signature/index.vue
  src/packages/__VUE/space/__tests__/space.spec.ts
  src/packages/__VUE/steps/__tests__/index.spec.tsx
  src/packages/__VUE/swipe/__tests__/swipe.spec.tsx
  src/packages/__VUE/table/__tests__/index.spec.ts
  src/packages/__VUE/uploader/index.taro.vue
  src/packages/utils/index.ts
  src/packages/utils/with-install.ts
  tsconfig.declaration.json
  tsconfig.declaration.taro.json
  vite.config.build.disperse.ts
  vite.config.build.taro.vue.disperse.ts
Labels: size/XL

#2840 refactor(divider): script setup
  package.json
  scripts/generate-script-setup.cjs
  src/config.json
  src/packages/__VUE/divider/__tests__/divider.spec.ts
  src/packages/__VUE/divider/divider.taro.vue
  src/packages/__VUE/divider/divider.vue
  src/packages/__VUE/divider/doc.en-US.md
  src/packages/__VUE/divider/doc.md
  src/packages/__VUE/divider/doc.taro.md
  src/packages/__VUE/divider/index.taro.ts
  src/packages/__VUE/divider/index.taro.vue
  src/packages/__VUE/divider/index.ts
  src/packages/__VUE/divider/index.vue
Labels: size/L

#2845 chore(checkbox): improve type def
  src/packages/__VUE/checkbox/index.taro.vue
  src/packages/__VUE/checkbox/index.vue
  src/packages/__VUE/checkbox/types.ts
Labels: size/M

#2848 chore(ellipsis): improve type def
  src/packages/__VUE/ellipsis/index.taro.vue
  src/packages/__VUE/ellipsis/index.vue
  src/packages/__VUE/ellipsis/types.ts
Labels: size/XS

#2843 fix: custom color border style
  src/packages/__VUE/button/__tests__/button.spec.ts
  src/packages/__VUE/button/button.taro.vue
  src/packages/__VUE/button/button.vue
Labels: size/M

#2849 chore: update peerDependencies
  publish/nutui-taro/package.json
  publish/nutui/package.json
Labels: size/XS

#2851 fix(form): 修复搭配 input 使用时的样式问题
  src/packages/__VUE/formitem/index.scss
Labels: size/XS

#2858 fix(side-navbar): remove unnecessary props
  src/packages/__VUE/sidenavbar/__tests__/index.spec.ts
  src/packages/__VUE/sidenavbar/doc.en-US.md
  src/packages/__VUE/sidenavbar/doc.md
  src/packages/__VUE/sidenavbar/doc.taro.md
  src/packages/__VUE/sidenavbar/index.scss
  src/packages/__VUE/sidenavbar/index.vue
  src/packages/__VUE/sidenavbaritem/index.taro.vue
  src/packages/__VUE/sidenavbaritem/index.vue
  src/packages/__VUE/subsidenavbar/index.scss
  src/packages/__VUE/subsidenavbar/index.taro.vue
  src/packages/__VUE/subsidenavbar/index.vue
Labels: size/M

#2860 fix(list): 优化 containerHeight 获取逻辑
  src/packages/__VUE/list/index.taro.vue
  src/packages/__VUE/list/index.vue
Labels: size/S

#2694 feat: new component calendar-card
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/custom-range.vue
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/disable.vue
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/first.vue
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/index.config.ts
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/index.vue
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/info.vue
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/multiple.vue
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/popup.vue
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/range.vue
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/ref.vue
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/single.vue
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/week.vue
  src/config.json
  src/packages/__VUE/calendarcard/__tests__/calendarcard.spec.tsx
  src/packages/__VUE/calendarcard/calendar-card.taro.vue
  src/packages/__VUE/calendarcard/calendar-card.vue
  src/packages/__VUE/calendarcard/demo/custom-range.vue
  src/packages/__VUE/calendarcard/demo/disable.vue
  src/packages/__VUE/calendarcard/demo/first.vue
  src/packages/__VUE/calendarcard/demo/index.vue
  src/packages/__VUE/calendarcard/demo/info.vue
  src/packages/__VUE/calendarcard/demo/multiple.vue
  src/packages/__VUE/calendarcard/demo/popup.vue
  src/packages/__VUE/calendarcard/demo/range.vue
  src/packages/__VUE/calendarcard/demo/ref.vue
  src/packages/__VUE/calendarcard/demo/single.vue
  src/packages/__VUE/calendarcard/demo/week.vue
  src/packages/__VUE/calendarcard/doc.en-US.md
  src/packages/__VUE/calendarcard/doc.md
  src/packages/__VUE/calendarcard/doc.taro.md
  src/packages/__VUE/calendarcard/icon.taro.ts
  src/packages/__VUE/calendarcard/icon.ts
  src/packages/__VUE/calendarcard/index.scss
  src/packages/__VUE/calendarcard/index.taro.ts
  src/packages/__VUE/calendarcard/index.ts
  src/packages/__VUE/calendarcard/types.ts
  src/packages/__VUE/calendarcard/utils.ts
  src/packages/locale/lang/baseLang.ts
  src/packages/locale/lang/en-US.ts
  src/packages/locale/lang/id-ID.ts
  src/packages/locale/lang/zh-CN.ts
  src/packages/locale/lang/zh-TW.ts
  src/packages/styles/variables-jdb.scss
  src/packages/styles/variables-jddkh.scss
  src/packages/styles/variables-jdt.scss
  src/packages/styles/variables.scss
Labels: size/XXL

#2866 chore(build): rename package entry
  .gitignore
  .prettierignore
  packages/nutui-taro-demo/src/app.ts
  scripts/generate-nutui-taro-vue.cjs
  scripts/generate-nutui.cjs
  scripts/generate-types-taro.cjs
  scripts/generate-types.cjs
  src/packages/__VUE/form/demo.vue
  src/packages/__VUE/icon/demo.vue
  src/packages/__VUE/imagepreview/demo.vue
  src/packages/__VUE/numberkeyboard/demo.vue
  src/packages/__VUE/picker/demo.vue
  src/packages/__VUE/pullrefresh/demo.vue
  src/packages/__VUE/shortpassword/demo.vue
  src/packages/__VUE/sku/demo.vue
  src/packages/__VUE/timeselect/demo.vue
  src/sites/mobile/main.ts
  tsconfig.declaration.json
  tsconfig.declaration.taro.json
  tsconfig.json
  vite.config.build.taro.vue.ts
  vite.config.build.ts
  vite.config.ts
Labels: size/M

#2868 chore(number-keyboard): improve type def
  src/packages/__VUE/numberkeyboard/index.taro.vue
  src/packages/__VUE/numberkeyboard/index.vue
  src/packages/__VUE/numberkeyboard/types.ts
Labels: size/XS

#2876 chore(deps): add jsdom to workspace
  package.json
  pnpm-lock.yaml
Labels: size/L

#2877 test: update vitest config
  vite.config.ts
  vitest.config.ts
Labels: size/M

#2878 fix(popover): 修复 popup 样式问题
  src/packages/__VUE/popover/index.scss
Labels: size/XS

#2881 test: migrate test environment to happy-dom
  package.json
  pnpm-lock.yaml
  src/packages/__VUE/actionsheet/__tests__/index.spec.ts
  src/packages/__VUE/address/__tests__/__snapshots__/address.spec.ts.snap
  src/packages/__VUE/avatar/__tests__/__snapshots__/avatar.spec.tsx.snap
  src/packages/__VUE/avatar/__tests__/avatar.spec.tsx
  src/packages/__VUE/avatarcropper/__tests__/__snapshots__/avatarcropper.spec.ts.snap
  src/packages/__VUE/avatarcropper/__tests__/avatarcropper.spec.ts
  src/packages/__VUE/button/__tests__/button.spec.ts
  src/packages/__VUE/card/__tests__/__snapshots__/index.spec.ts.snap
  src/packages/__VUE/cascader/__tests__/__snapshots__/cascader.spec.ts.snap
  src/packages/__VUE/cell/__tests__/__snapshots__/cell.spec.ts.snap
  src/packages/__VUE/checkbox/__tests__/__snapshots__/checkbox.spec.tsx.snap
  src/packages/__VUE/checkbox/__tests__/checkbox.spec.ts
  src/packages/__VUE/checkbox/__tests__/checkbox.spec.tsx
  src/packages/__VUE/checkboxgroup/__tests__/checkboxgroup.spec.ts
  src/packages/__VUE/checkboxgroup/__tests__/checkboxgroup.spec.tsx
  src/packages/__VUE/dialog/__tests__/__snapshots__/function.spec.ts.snap
  src/packages/__VUE/dialog/__tests__/function.spec.ts
  src/packages/__VUE/dialog/__tests__/index.spec.ts
  src/packages/__VUE/divider/__tests__/divider.spec.ts
  src/packages/__VUE/ecard/__tests__/__snapshots__/index.spec.ts.snap
  src/packages/__VUE/ellipsis/__tests__/ellipsis.spec.ts
  src/packages/__VUE/notify/__tests__/function.spec.ts
  src/packages/__VUE/radio/__tests__/radio.spec.tsx
  src/packages/__VUE/radiogroup/__tests__/radiogroup.spec.ts
  src/packages/__VUE/range/__tests__/range.spec.ts
  src/packages/__VUE/sidenavbar/__tests__/index.spec.ts
  src/packages/__VUE/sidenavbar/__tests__/index.spec.tsx
  src/packages/__VUE/skeleton/__tests__/__snapshots__/skeleton.spec.ts.snap
  src/packages/__VUE/steps/__tests__/__snapshots__/index.spec.tsx.snap
  src/packages/__VUE/sticky/__tests__/__snapshots__/index.spec.ts.snap
  src/packages/__VUE/tabbar/__tests__/__snapshots__/index.spec.tsx.snap
  src/packages/__VUE/tabbar/__tests__/index.spec.tsx
  src/packages/__VUE/tabs/__tests__/index.spec.tsx
  src/packages/__VUE/timeselect/__tests__/timeselect.spec.ts
  src/packages/__VUE/tour/__tests__/tour.spec.ts
  src/packages/__VUE/trendarrow/__tests__/trendarrow.spec.ts
  src/packages/__VUE/uploader/__tests__/__snapshots__/index.spec.ts.snap
  src/packages/__VUE/video/__tests__/__snapshots__/video.spec.ts.snap
  vite.config.ts
Labels: size/XXL

#2882 test(collapse): update test
  src/packages/__VUE/collapse/__tests__/collapse.spec.tsx
Labels: size/S

#2884 test(icon): add unit test
  src/packages/__VUE/icon/__tests__/index.spec.tsx
Labels: size/S

#2865 fix: 微信真机调试选择头像的canvas层级错误(#2836)
  src/packages/__VUE/avatarcropper/index.scss
  src/packages/__VUE/avatarcropper/index.taro.vue
  src/packages/__VUE/avatarcropper/index.vue
Labels: size/M

#2898 chore(popup, notify): improve type def
  src/packages/__VUE/cascader/index.taro.vue
  src/packages/__VUE/notify/index.taro.vue
  src/packages/__VUE/notify/index.ts
  src/packages/__VUE/notify/index.vue
  src/packages/__VUE/notify/types.ts
  src/packages/__VUE/popup/props.ts
  src/packages/__VUE/popup/types.ts
Labels: size/M

#2900 chore(button, divider): add withDefault
  src/packages/__VUE/button/button.taro.vue
  src/packages/__VUE/button/button.vue
  src/packages/__VUE/button/doc.en-US.md
  src/packages/__VUE/button/doc.md
  src/packages/__VUE/button/doc.taro.md
  src/packages/__VUE/button/index.taro.ts
  src/packages/__VUE/button/index.ts
  src/packages/__VUE/divider/divider.taro.vue
  src/packages/__VUE/divider/divider.vue
  src/packages/__VUE/divider/doc.en-US.md
  src/packages/__VUE/divider/doc.md
  src/packages/__VUE/divider/doc.taro.md
  src/packages/__VUE/divider/index.taro.ts
  src/packages/__VUE/divider/index.ts
Labels: size/L

#2901 refactor(button): remove toRefs
  src/packages/__VUE/button/button.taro.vue
  src/packages/__VUE/button/button.vue
Labels: size/M

#2902 chore(calendar-card): update demo & docs
  packages/nutui-taro-demo/config/index.js
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/disable.vue
  packages/nutui-taro-demo/src/dentry/pages/calendarcard/ref.vue
  packages/nutui-taro-demo/tsconfig.json
  scripts/generate-script-setup.cjs
  src/packages/__VUE/calendarcard/calendar-card.taro.vue
  src/packages/__VUE/calendarcard/calendar-card.vue
  src/packages/__VUE/calendarcard/demo/disable.vue
  src/packages/__VUE/calendarcard/demo/ref.vue
  src/packages/__VUE/calendarcard/doc.en-US.md
  src/packages/__VUE/calendarcard/doc.md
  src/packages/__VUE/calendarcard/doc.taro.md
  src/packages/__VUE/calendarcard/index.taro.ts
  src/packages/__VUE/calendarcard/index.ts
Labels: size/L

#2903 fix(inputnumber): 组件输入内容不会触发change事件(#2880)
  src/packages/__VUE/inputnumber/index.taro.vue
  src/packages/__VUE/inputnumber/index.vue
Labels: size/XS

#2908 fix(utils): is-window
  src/packages/utils/useRect/index.ts
  src/packages/utils/useTaroRect/index.ts
Labels: size/XS
